services:
  db:
    image: postgres
    container_name: postgres_spring_batch
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_spring_batch